### ISSUE TITLE
Day names

### ISSUE THREAD

**Issue by D4R4** [tahajahangir/jdate#6]
Hi,
Is there a function to get the day names in Farsi like شنبه ?

**Comment by tahajahangir** [comment]
Thanks for taking the time to report. Unfortunately no, because the original `Date` class has no functionality to formate dates, and so this library has no formatting capabilities.

The main purpose of this library is to replace the `Date` class and provide the same functionality, but it's welcome for PRs if you want add other functions for formatting.
